services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: flowtrack-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: flowtrack
      RABBITMQ_DEFAULT_PASS: flowtrack
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      flowtrack:
        aliases:
          - flowtrack-rabbitmq
    volumes:
      - ./rabbitmq_plugins:/etc/rabbitmq/enabled_plugins

  adminer:
    image: adminer
    container_name: adminer
    networks:
      flowtrack:
        aliases:
          - adminer
    ports:
      - '8081:8080'

  elasticsearch-monitoring:
    image: elasticsearch:9.4.2
    container_name: flowtrack-logs-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - http.cors.enabled=true
      - "http.cors.allow-origin=http://localhost:8082"
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      flowtrack-monitoring:
        aliases:
          - flowtrack-elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:9.4.2
    container_name: flowtrack-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-monitoring:9200
      - XPACK_FLEET_ENABLED=false
    ports:
      - '5601:5601'
    networks:
      flowtrack-monitoring:
        aliases:
          - flowtrack-kibana
    depends_on:
      - elasticsearch-monitoring

networks:
  flowtrack:
    driver: bridge
    name: flowtrack
  flowtrack-monitoring:
    driver: bridge
    name: flowtrack-monitoring

volumes:
  elasticsearch-data:
