apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-workmanagement
  namespace: flowtrack
spec:
  ports:
  - port: 9200
    name: http
  - port: 9300
    name: transport
  selector:
    app: elasticsearch-workmanagement
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-workmanagement
  namespace: flowtrack
spec:
  serviceName: elasticsearch-workmanagement
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-workmanagement
  template:
    metadata:
      labels:
        app: elasticsearch-workmanagement
    spec:
      initContainers:
      - name: sysctl
        image: busybox:1.28
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: elasticsearch:9.4.2
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        env:
        - name: discovery.type
          value: single-node
        - name: xpack.security.enabled
          value: "false"
        - name: xpack.ml.enabled
          value: "false"
        - name: xpack.graph.enabled
          value: "false"
        - name: xpack.watcher.enabled
          value: "false"
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: http.cors.enabled
          value: "true"
        - name: http.cors.allow-origin
          value: "http://kibana:5601"
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
