services:
  postgres:
    image: postgres:18-alpine
    container_name: flowtrack-db
    environment:
      POSTGRES_USER: flowtrack
      POSTGRES_PASSWORD: flowtrack
      POSTGRES_DB: flowtrack
    ports:
      - '5432:5432'
    networks:
      flowtrack:
        aliases:
          - flowtrack-db
    volumes:
      - flowtrack:/var/lib/postgresql

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: flowtrack-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: flowtrack
      RABBITMQ_DEFAULT_PASS: flowtrack
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      flowtrack:
        aliases:
          - flowtrack-rabbitmq
    volumes:
      - ./rabbitmq_plugins:/etc/rabbitmq/enabled_plugins

  adminer:
    image: adminer
    container_name: adminer
    networks:
      flowtrack:
        aliases:
          - adminer
    ports:
      - '8081:8080'

  elasticsearch:
    image: elasticsearch:9.4.2
    container_name: flowtrack-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - http.cors.enabled=true
      - "http.cors.allow-origin=http://localhost:8082"
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      flowtrack:
        aliases:
          - flowtrack-elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  elasticvue:
    image: cars10/elasticvue
    container_name: flowtrack-elasticvue
    ports:
      - '8082:8080'
    networks:
      flowtrack:
        aliases:
          - flowtrack-elasticvue

networks:
  flowtrack:
    driver: bridge
    name: flowtrack

volumes:
  flowtrack:
    driver: local
  elasticsearch-data:
    driver: local
