services:
  postgres:
    image: postgres:18-alpine
    container_name: flowtrack-db
    environment:
      POSTGRES_USER: flowtrack
      POSTGRES_PASSWORD: flowtrack
      POSTGRES_DB: flowtrack
    ports:
      - '5432:5432'
    networks:
      flowtrack:
        aliases:
          - flowtrack-db
    volumes:
      - flowtrack:/var/lib/postgresql


  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: flowtrack-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: flowtrack
      RABBITMQ_DEFAULT_PASS: flowtrack
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      flowtrack:
        aliases:
          - flowtrack-rabbitmq
    volumes:
      - ./rabbitmq_plugins:/etc/rabbitmq/enabled_plugins

  adminer:
    image: adminer
    container_name: adminer
    networks:
      flowtrack:
        aliases:
          - adminer
    ports:
      - '8081:8080'

networks:
  flowtrack:
    driver: bridge
    name: flowtrack

volumes:
  flowtrack:
    driver: local
