filebeat.inputs:
- type: filestream
  id: flowtrack-logs
  enabled: true
  paths:
    - /var/log/flowtrack/*.json
  parsers:
    - ndjson:
        keys_under_root: true
        add_error_key: true
        overwrite_keys: true
        message_key: messageTemplate

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

logging.level: warning
