<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="dotenv.net" Version="4.0.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../contexts/Iam/FlowTrack.Iam.csproj" />
  </ItemGroup>
  <Target
    Name="Husky"
    AfterTargets="Restore"
    Condition="'$(HUSKY)' != 0"
    Inputs="../../../.config/dotnet-tools.json"
    Outputs="../../../.husky/_/install.stamp"
  >
    <Exec
      Command="dotnet tool restore"
      StandardOutputImportance="Low"
      StandardErrorImportance="High"
    />
    <Exec
      Command="dotnet husky install"
      StandardOutputImportance="Low"
      StandardErrorImportance="High"
      WorkingDirectory="../../.."
    />
    <Touch
      Files="../../../.husky/_/install.stamp"
      AlwaysCreate="true"
      Condition="Exists('../../../.husky/_')"
    />
    <ItemGroup>
      <FileWrites Include="../../../.husky/_/install.stamp" />
    </ItemGroup>
  </Target>
</Project>
