<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <UserSecretsId>93476a9e-d832-4043-b50b-94647278e2d6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Docker.DotNet" Version="3.125.15" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.12.0" />
    <PackageReference Include="Testcontainers.RabbitMq" Version="4.12.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="User/" />
    <Folder Include="User/application/" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/contexts/iam/FlowTrack.Iam.csproj" />
    <ProjectReference Include="../Shared/FlowTrack.Shared.Test.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>FlowtrackApiTest</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
